# action.yml
# https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
name: 'octodns-sync'
description: 'Run octodns/octodns to deploy your DNS config to any cloud.'
inputs:
  add_pr_comment:
    description: 'Add plan as a comment, when triggered by a pull request?'
    required: true
    default: 'No'
  config_path:
    description: 'Path, relative to your repository root, of the config file
                  you would like octodns to use.'
    required: true
    default: 'public.yaml'
  doit:
    description: 'Really do it? Set "--doit" to do it; Any other string to
                  not do it.'
    required: false
    default: ''
  pr_comment_token:
    description: 'Provide a token to use, if you set add_pr_comment to Yes.'
    required: true
    default: 'Not set'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/solvaholic/octodns-sync:2.1.3'
  env:
    ADD_PR_COMMENT: ${{ inputs.add_pr_comment }}
    PR_COMMENT_TOKEN: ${{ inputs.pr_comment_token }}
  args:
    - ${{ inputs.config_path }}
    - ${{ inputs.doit }}

branding:
  icon: 'list'
  color: 'purple'
